In [93]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [94]:
Expenditure = pd.read_csv('Expenditure on Completed and On-going Works as on Date.csv')
Expenditure

C:\Users\Manav Motiramani\AppData\Local\Temp\ipykernel_29332\3624428416.py:1: DtypeWarning: Columns (0: Sr. No., 1: Fund Disbursed Amount ( ₹ )) have mixed types. Specify dtype option on import or set low_memory=False.
  Expenditure = pd.read_csv('Expenditure on Completed and On-going Works as on Date.csv')

,Sr. No.,State,Work,Work ID,IDA,Hon'ble Members of Parliament,Constituency,Expenditure Date,Vendor Name,Payment Status,Fund Disbursed Amount ( ₹ )
0,1,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233777,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,21-Aug-2026,DARSH BUILDCON,Payment In-Progress,799146.0
1,2,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233878,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,832080.0
2,3,Uttar Pradesh,"Construction of roads, link roads, pathways or...",WS/MP18218/2025-2026/233781,GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA),ATUL GARG,GHAZIABAD,04-Aug-2026,DARSH BUILDCON,Payment In-Progress,498309.0
3,4,Odisha,Construction of community centers and communit...,WS/MP370/2024-2025/145537,Sundaragada(DISTRICT COLLECTOR SUNDARGARH_IDA),Shri Jual Oram,SUNDARGARH (ST),31-Aug-2026,MEMBER SECY OB AND OC WWB BBSR,Payment In-Progress,2000.0
4,5,Karnataka,Installing tube-wells and borewells,WS/MP18093/2026-2027/217130,TUMAKURU(DEPUTY COMMISSIONER TUMKUR_IDA),V. SOMANNA,TUMKUR,27-Jul-2026,KRIDL BHUSIRI ACCOUNT WORKS,Payment In-Progress,375000.0
...,...,...,...,...,...,...,...,...,...,...,...
84048,84049,Odisha,Construction of community centers and communit...,WS/MP18148/2025-2026/170300,NABARANGPUR(DISTRICT COLLECTOR NABARANGPUR_IDA),BALABHADRA MAJHI,NABARANGPUR(ST),07-Apr-2026,MEMBER SECY OB AND OC WWB BBSR,Payment Success,2000
84049,84050,Odisha,Construction of community centers and communit...,WS/MP18148/2025-2026/170188,NABARANGPUR(DISTRICT COLLECTOR NABARANGPUR_IDA),BALABHADRA MAJHI,NABARANGPUR(ST),19-Mar-2026,MEMBER SECY OB AND OC WWB BBSR,Payment Success,5000
84050,84051,Odisha,Construction of rooms and halls in school and ...,WS/MP18148/2025-2026/170297,NABARANGPUR(DISTRICT COLLECTOR NABARANGPUR_IDA),BALABHADRA MAJHI,NABARANGPUR(ST),18-Feb-2026,MEMBER SECY OB AND OC WWB BBSR,Payment Success,5000
84051,84052,Odisha,Construction of boundary walls of existing pub...,WS/MP18141/2025-2026/239835,DHENKANAL(DISTRICT COLLECTOR DHENKANAL_IDA),RUDRA NARAYAN PANY,DHENKANAL,17-Jul-2026,MEMBER SECY OB AND OC WWB BBSR,Payment Success,5000
84052,Grand Total,,,,,,,,,,"27,73,10,02,238.45"

In [95]:
Completed = pd.read_csv('Works Completed.csv')
Completed.rename(columns={"Work": "Work_Id"}, inplace=True)
Completed["Work"] = Completed["Work_Id"].str.rsplit("-", n=1).str[1].str.strip()
Completed["Work_Id"] = Completed["Work_Id"].str.rsplit("-", n=1).str[0]
Completed[["MP_ID", "Financial_Year"]] = Completed["Work_Id"].str.split("/", expand=True).iloc[:, 1:3]
Completed['Work_Id'] = Completed['Work_Id'].str.split("/").str[3]
Completed

,Sr. No.,Work Category,Work_Id,State,IDA,Work Description,Hon'ble Members of Parliament,Constituency,Image,Completion Date,Amount Disbursed ( ₹ ),Work,MP_ID,Financial_Year
0,1,Normal/Others,133409,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,NaN,05-Sep-2024,448127,"Construction of roads, link roads, pathways or...",MP418,2024-2025
1,2,Normal/Others,133691,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
2,3,Normal/Others,134140,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,NaN,12-Aug-2024,293492,"Construction of roads, link roads, pathways or...",MP345,2024-2025
3,4,Normal/Others,133686,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
4,5,Normal/Others,133690,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34281,34282,Normal/Others,263443,Gujarat,RAJKOT(DISTRICT COLLECTOR RAJKOT_IDA),Paver Block from main road to village gate dif...,PARSHOTTAMBHAI RUPALA,RAJKOT,Images,02-Sep-2026,400000,"Construction of roads, link roads, pathways or...",MP18056,2025-2026
34282,34283,Normal/Others,250043,Delhi,CENTRAL(COMMISSIONER MCD (CENTRAL DISTRICT)),Provision of lighting arrangement,Bansuri Swaraj,NEW DELHI,Images,03-Sep-2026,649381,Lighting of public spaces,MP18397,2025-2026
34283,34284,Normal/Others,253823,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Construction or creation of road with drainage...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,04-Sep-2026,499480,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34284,34285,Normal/Others,253828,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Creation of concrete road from house of Prasha...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,03-Sep-2026,497769,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34285,Grand Total,,NaN,,,,,,,,"16,58,62,02,068.4",NaN,None,None

In [96]:
Recommended = pd.read_csv('Works Recommended.csv')
Recommended.rename(columns={"WORK": "Work_Id"}, inplace=True)

C:\Users\Manav Motiramani\AppData\Local\Temp\ipykernel_29332\171487503.py:1: DtypeWarning: Columns (0: Sr. No., 1: RECOMMENDED AMOUNT   ( ₹ )) have mixed types. Specify dtype option on import or set low_memory=False.
  Recommended = pd.read_csv('Works Recommended.csv')

In [97]:
Recommended["Work"] = Recommended["Work_Id"].str.rsplit("-", n=1).str[1].str.strip()
Recommended["Work_Id"] = Recommended["Work_Id"].str.rsplit("-", n=1).str[0]
Recommended[["MP_ID", "Financial_Year"]] = Recommended["Work_Id"].str.split("/", expand=True).iloc[:, 1:3]
Recommended['Work_Id'] = Recommended['Work_Id'].str.split("/").str[3]
Recommended

,Sr. No.,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Sanction Date,Work,MP_ID,Financial_Year
0,1,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-2024,497185.0,09-Jul-2024,Construction of buildings for community cultur...,\t MP620,2024-2025
1,2,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-2024,500000.0,18-Sep-2025,Construction of rooms and halls in school and ...,\t MP620,2025-2026
2,3,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-2024,450000.0,23-Sep-2024,Construction of buildings for community cultur...,\t MP620,2024-2025
3,4,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-2024,1500000.0,29-May-2025,Construction of buildings for community cultur...,\t MP620,2025-2026
4,5,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-2024,398009.0,22-Aug-2024,Construction of buildings for community cultur...,\t MP620,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106515,106516,Normal/Others,NaN,Telangana,HANUMAKONDA(DISTRICT COLLECTOR HANUMAKONDA_IDA),CHAMALA KIRAN KUMAR REDDY,BHONGIR,Providing CC Camera at velair village,13-Sep-2025,499000,NaN,Providing CCTV camera system for security of p...,None,None
106516,106517,Normal/Others,NaN,Telangana,NIZAMABAD(DISTRICT COLLECTOR NIZAMABAD_IDA),Arvind Dharmapuri,NIZAMABAD,Construction of Community hall in BC wada40,28-Oct-2024,400000,NaN,Construction of community centers and communit...,None,None
106517,106518,Normal/Others,NaN,Telangana,JANGOAN(DISTRICT COLLECTOR JANGAON_IDA),Kishan Reddy Gangapuram,SECUNDERABAD,Laying of CC Road from R&B BT Road at Mamidala...,22-Jun-2026,1000000,NaN,"Construction of roads, link roads, pathways or...",None,None
106518,106519,Normal/Others,NaN,Telangana,RAJANNA SIRCILLA(DISTRICT COLLECTOR RAJANNA SI...,VAMSI KRISHNA GADDAM,PEDDAPALLE,Drilling of borewell and Fitting of pump set a...,13-Jul-2026,250000,NaN,wells and borewells,None,None
106519,Grand Total,,NaN,,,,,,,,"57,08,49,11,299.85",NaN,None,None

In [98]:
Recommended["MP_ID"] = Recommended["MP_ID"].str.strip()
Recommended

,Sr. No.,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Sanction Date,Work,MP_ID,Financial_Year
0,1,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-2024,497185.0,09-Jul-2024,Construction of buildings for community cultur...,MP620,2024-2025
1,2,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-2024,500000.0,18-Sep-2025,Construction of rooms and halls in school and ...,MP620,2025-2026
2,3,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-2024,450000.0,23-Sep-2024,Construction of buildings for community cultur...,MP620,2024-2025
3,4,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-2024,1500000.0,29-May-2025,Construction of buildings for community cultur...,MP620,2025-2026
4,5,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-2024,398009.0,22-Aug-2024,Construction of buildings for community cultur...,MP620,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106515,106516,Normal/Others,NaN,Telangana,HANUMAKONDA(DISTRICT COLLECTOR HANUMAKONDA_IDA),CHAMALA KIRAN KUMAR REDDY,BHONGIR,Providing CC Camera at velair village,13-Sep-2025,499000,NaN,Providing CCTV camera system for security of p...,None,None
106516,106517,Normal/Others,NaN,Telangana,NIZAMABAD(DISTRICT COLLECTOR NIZAMABAD_IDA),Arvind Dharmapuri,NIZAMABAD,Construction of Community hall in BC wada40,28-Oct-2024,400000,NaN,Construction of community centers and communit...,None,None
106517,106518,Normal/Others,NaN,Telangana,JANGOAN(DISTRICT COLLECTOR JANGAON_IDA),Kishan Reddy Gangapuram,SECUNDERABAD,Laying of CC Road from R&B BT Road at Mamidala...,22-Jun-2026,1000000,NaN,"Construction of roads, link roads, pathways or...",None,None
106518,106519,Normal/Others,NaN,Telangana,RAJANNA SIRCILLA(DISTRICT COLLECTOR RAJANNA SI...,VAMSI KRISHNA GADDAM,PEDDAPALLE,Drilling of borewell and Fitting of pump set a...,13-Jul-2026,250000,NaN,wells and borewells,None,None
106519,Grand Total,,NaN,,,,,,,,"57,08,49,11,299.85",NaN,None,None

In [99]:
Sanctioned = pd.read_csv('Works Sanctioned.csv')
Sanctioned.rename(columns={"Work": "Work_Id"}, inplace=True)
Sanctioned["Work"] = Sanctioned["Work_Id"].str.rsplit("-", n=1).str[1].str.strip()
Sanctioned["Work_Id"] = Sanctioned["Work_Id"].str.rsplit("-", n=1).str[0]
Sanctioned[["MP_ID", "Financial_Year"]] = Sanctioned["Work_Id"].str.split("/", expand=True).iloc[:, 1:3]
Sanctioned['Work_Id'] = Sanctioned['Work_Id'].str.split("/").str[3]
Sanctioned

C:\Users\Manav Motiramani\AppData\Local\Temp\ipykernel_29332\3621874116.py:1: DtypeWarning: Columns (0: Sr. No., 1: Sanction Amount ( ₹ )) have mixed types. Specify dtype option on import or set low_memory=False.
  Sanctioned = pd.read_csv('Works Sanctioned.csv')

,Sr. No.,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status,Work,MP_ID,Financial_Year
0,1,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-2024,09-Jul-2024,497185.0,Physical Inspection,Construction of buildings for community cultur...,\t MP620,2024-2025
1,2,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-2024,18-Sep-2025,500000.0,Sanction,Construction of rooms and halls in school and ...,\t MP620,2025-2026
2,3,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-2024,23-Sep-2024,450000.0,Sanction,Construction of buildings for community cultur...,\t MP620,2024-2025
3,4,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-2024,29-May-2025,1500000.0,Work partially Completed,Construction of buildings for community cultur...,\t MP620,2025-2026
4,5,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-2024,22-Aug-2024,398009.0,Physical Inspection,Construction of buildings for community cultur...,\t MP620,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79089,79090,Normal/Others,307761,Uttar Pradesh,BUDAUN(DISTRICT MAGISTRATE BUDAUN_IDA),ADITYA YADAV,BADAUN,malikpur mein bisouli bagrain ke pas devsthan ...,25-Aug-2026,01-Sep-2026,303500,Vendor Identification,Installing community drinking water plants,MP18203,2026-2027
79090,79091,Normal/Others,307762,Uttar Pradesh,BUDAUN(DISTRICT MAGISTRATE BUDAUN_IDA),ADITYA YADAV,BADAUN,kasba bisouli mein civil bar bisoli prangan me...,25-Aug-2026,01-Sep-2026,303500,Vendor Identification,Installing community drinking water plants,MP18203,2026-2027
79091,79092,Normal/Others,308754-Construction of bus-sheds or bus,Tamil Nadu,TIRUPPUR(DISTRICT COLLECTOR TIRUPPUR_IDA),GANAPATHY RAJKUMAR P,COIMBATORE,Construction of Passenger Shelter at Agrahara ...,01-Sep-2026,01-Sep-2026,800000,Physical Inspection,stops,MP18174,2026-2027
79092,79093,Normal/Others,312057,Andhra Pradesh,PRAKASAM(DISTRICT COLLECTOR PRAKASAM_IDA),Magunta Sreenivasulu Reddy,ONGOLE,Providing an additional Block for 20 Bedded Di...,03-Sep-2026,03-Sep-2026,4000000,Sanction,Construction of rooms and facilities for hospi...,MP403,2026-2027
79093,Grand Total,,NaN,,,,,,,,,"41,69,90,74,346.88",NaN,None,None

In [100]:
Sanctioned["MP_ID"] = Sanctioned["MP_ID"].str.strip()
Sanctioned

,Sr. No.,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status,Work,MP_ID,Financial_Year
0,1,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,08-Jul-2024,09-Jul-2024,497185.0,Physical Inspection,Construction of buildings for community cultur...,MP620,2024-2025
1,2,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,08-Jul-2024,18-Sep-2025,500000.0,Sanction,Construction of rooms and halls in school and ...,MP620,2025-2026
2,3,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,08-Jul-2024,23-Sep-2024,450000.0,Sanction,Construction of buildings for community cultur...,MP620,2024-2025
3,4,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,08-Jul-2024,29-May-2025,1500000.0,Work partially Completed,Construction of buildings for community cultur...,MP620,2025-2026
4,5,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,09-Jul-2024,22-Aug-2024,398009.0,Physical Inspection,Construction of buildings for community cultur...,MP620,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79089,79090,Normal/Others,307761,Uttar Pradesh,BUDAUN(DISTRICT MAGISTRATE BUDAUN_IDA),ADITYA YADAV,BADAUN,malikpur mein bisouli bagrain ke pas devsthan ...,25-Aug-2026,01-Sep-2026,303500,Vendor Identification,Installing community drinking water plants,MP18203,2026-2027
79090,79091,Normal/Others,307762,Uttar Pradesh,BUDAUN(DISTRICT MAGISTRATE BUDAUN_IDA),ADITYA YADAV,BADAUN,kasba bisouli mein civil bar bisoli prangan me...,25-Aug-2026,01-Sep-2026,303500,Vendor Identification,Installing community drinking water plants,MP18203,2026-2027
79091,79092,Normal/Others,308754-Construction of bus-sheds or bus,Tamil Nadu,TIRUPPUR(DISTRICT COLLECTOR TIRUPPUR_IDA),GANAPATHY RAJKUMAR P,COIMBATORE,Construction of Passenger Shelter at Agrahara ...,01-Sep-2026,01-Sep-2026,800000,Physical Inspection,stops,MP18174,2026-2027
79092,79093,Normal/Others,312057,Andhra Pradesh,PRAKASAM(DISTRICT COLLECTOR PRAKASAM_IDA),Magunta Sreenivasulu Reddy,ONGOLE,Providing an additional Block for 20 Bedded Di...,03-Sep-2026,03-Sep-2026,4000000,Sanction,Construction of rooms and facilities for hospi...,MP403,2026-2027
79093,Grand Total,,NaN,,,,,,,,,"41,69,90,74,346.88",NaN,None,None

In [101]:
Completed

,Sr. No.,Work Category,Work_Id,State,IDA,Work Description,Hon'ble Members of Parliament,Constituency,Image,Completion Date,Amount Disbursed ( ₹ ),Work,MP_ID,Financial_Year
0,1,Normal/Others,133409,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,NaN,05-Sep-2024,448127,"Construction of roads, link roads, pathways or...",MP418,2024-2025
1,2,Normal/Others,133691,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
2,3,Normal/Others,134140,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,NaN,12-Aug-2024,293492,"Construction of roads, link roads, pathways or...",MP345,2024-2025
3,4,Normal/Others,133686,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
4,5,Normal/Others,133690,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,07-Apr-2025,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34281,34282,Normal/Others,263443,Gujarat,RAJKOT(DISTRICT COLLECTOR RAJKOT_IDA),Paver Block from main road to village gate dif...,PARSHOTTAMBHAI RUPALA,RAJKOT,Images,02-Sep-2026,400000,"Construction of roads, link roads, pathways or...",MP18056,2025-2026
34282,34283,Normal/Others,250043,Delhi,CENTRAL(COMMISSIONER MCD (CENTRAL DISTRICT)),Provision of lighting arrangement,Bansuri Swaraj,NEW DELHI,Images,03-Sep-2026,649381,Lighting of public spaces,MP18397,2025-2026
34283,34284,Normal/Others,253823,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Construction or creation of road with drainage...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,04-Sep-2026,499480,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34284,34285,Normal/Others,253828,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Creation of concrete road from house of Prasha...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,03-Sep-2026,497769,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34285,Grand Total,,NaN,,,,,,,,"16,58,62,02,068.4",NaN,None,None

In [102]:
Completed.drop(columns=["Sr. No."], inplace=True)

In [103]:
Recommended.drop(columns=["Sr. No."], inplace=True)
Sanctioned.drop(columns=["Sr. No."], inplace=True)

In [104]:
Completed["Completion Date"] = pd.to_datetime(
    Completed["Completion Date"],
    format="%d-%b-%Y",
    errors="coerce"
)
Completed

,Work Category,Work_Id,State,IDA,Work Description,Hon'ble Members of Parliament,Constituency,Image,Completion Date,Amount Disbursed ( ₹ ),Work,MP_ID,Financial_Year
0,Normal/Others,133409,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,NaN,2024-09-05,448127,"Construction of roads, link roads, pathways or...",MP418,2024-2025
1,Normal/Others,133691,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,2025-04-07,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
2,Normal/Others,134140,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,NaN,2024-08-12,293492,"Construction of roads, link roads, pathways or...",MP345,2024-2025
3,Normal/Others,133686,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,2025-04-07,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
4,Normal/Others,133690,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,2025-04-07,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34281,Normal/Others,263443,Gujarat,RAJKOT(DISTRICT COLLECTOR RAJKOT_IDA),Paver Block from main road to village gate dif...,PARSHOTTAMBHAI RUPALA,RAJKOT,Images,2026-09-02,400000,"Construction of roads, link roads, pathways or...",MP18056,2025-2026
34282,Normal/Others,250043,Delhi,CENTRAL(COMMISSIONER MCD (CENTRAL DISTRICT)),Provision of lighting arrangement,Bansuri Swaraj,NEW DELHI,Images,2026-09-03,649381,Lighting of public spaces,MP18397,2025-2026
34283,Normal/Others,253823,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Construction or creation of road with drainage...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,2026-09-04,499480,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34284,Normal/Others,253828,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Creation of concrete road from house of Prasha...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,2026-09-03,497769,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34285,,NaN,,,,,,,NaT,"16,58,62,02,068.4",NaN,None,None

In [105]:
Recommended["Recommended date"] = pd.to_datetime(
    Recommended["Recommended date"],
    format="%d-%b-%Y",
    errors="coerce"
)
Sanctioned["Recommended date"] = pd.to_datetime(
    Sanctioned["Recommended date"],
    format="%d-%b-%Y",
    errors="coerce"
)
Sanctioned["Sanction Date"] = pd.to_datetime(
    Sanctioned["Sanction Date"],
    format="%d-%b-%Y",
    errors="coerce"
)

In [106]:

Completed

,Work Category,Work_Id,State,IDA,Work Description,Hon'ble Members of Parliament,Constituency,Image,Completion Date,Amount Disbursed ( ₹ ),Work,MP_ID,Financial_Year
0,Normal/Others,133409,Bihar,ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA),PCC Road from Permeshwar Bhagat house to Ramde...,Pradeep Kumar Singh,ARARIA,NaN,2024-09-05,448127,"Construction of roads, link roads, pathways or...",MP418,2024-2025
1,Normal/Others,133691,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,2025-04-07,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
2,Normal/Others,134140,Kerala,KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA),Concreting of road from Janathavayanasala - P...,Shri NK Premachandran,KOLLAM,NaN,2024-08-12,293492,"Construction of roads, link roads, pathways or...",MP345,2024-2025
3,Normal/Others,133686,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,2025-04-07,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
4,Normal/Others,133690,Punjab,FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA),Construction of MID DAY Meal Shed in Govt Prim...,SARABJEET SINGH KHALSA,FARIDKOT(SC),NaN,2025-04-07,300000,Construction of rooms and halls in school and ...,MP18152,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34281,Normal/Others,263443,Gujarat,RAJKOT(DISTRICT COLLECTOR RAJKOT_IDA),Paver Block from main road to village gate dif...,PARSHOTTAMBHAI RUPALA,RAJKOT,Images,2026-09-02,400000,"Construction of roads, link roads, pathways or...",MP18056,2025-2026
34282,Normal/Others,250043,Delhi,CENTRAL(COMMISSIONER MCD (CENTRAL DISTRICT)),Provision of lighting arrangement,Bansuri Swaraj,NEW DELHI,Images,2026-09-03,649381,Lighting of public spaces,MP18397,2025-2026
34283,Normal/Others,253823,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Construction or creation of road with drainage...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,2026-09-04,499480,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34284,Normal/Others,253828,Maharashtra,SATARA(DISTRICT COLLECTOR SATARA_IDA),Creation of concrete road from house of Prasha...,SHRIMANT CHH UDAYANRAJE PRATAPSINHAMAHARAJ BHO...,SATARA,Images,2026-09-03,497769,"Construction of roads, link roads, pathways or...",MP18133,2025-2026
34285,,NaN,,,,,,,NaT,"16,58,62,02,068.4",NaN,None,None

In [107]:
Sanctioned[Sanctioned['Work_Id'].isin(
    Completed.loc[Completed['Work Description'].isnull(), 'Work_Id']
)]

,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status,Work,MP_ID,Financial_Year
852,Normal/Others,136940-Installing tube,Bihar,KAIMUR (BHABUA)(DISTRICT PLANNING OFFICER KAIM...,SUDHAKAR SINGH,BUXAR,NaN,2024-08-25,2025-01-15,279921.0,Physical Inspection,wells and borewells,MP18032,2024-2025
894,Normal/Others,137009-Installing tube,Bihar,KAIMUR (BHABUA)(DISTRICT PLANNING OFFICER KAIM...,SUDHAKAR SINGH,BUXAR,NaN,2024-08-25,2024-12-09,231640.0,Physical Inspection,wells and borewells,MP18032,2024-2025
895,Normal/Others,137010-Installing tube,Bihar,BUXAR(DISTRICT PLANNING OFFICER BUXAR_IDA),SUDHAKAR SINGH,BUXAR,NaN,2024-08-25,2024-12-20,183187.0,Physical Inspection,wells and borewells,MP18032,2024-2025
898,Normal/Others,137015,Bihar,KAIMUR (BHABUA)(DISTRICT PLANNING OFFICER KAIM...,SUDHAKAR SINGH,BUXAR,NaN,2024-08-25,2025-01-07,791481.0,Physical Inspection,Construction of public libraries and reading r...,MP18032,2024-2025
4251,Normal/Others,143830,Madhya Pradesh,SHIVPURI(District Collector Shivpuri_IDA),JYOTIRADITYA M. SCINDIA,GUNA,NaN,2024-09-26,2024-09-27,585000.0,Physical Inspection,Purchase of mobile water tankers,MP18357,2024-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31645,Normal/Others,195602,Uttar Pradesh,BAREILLY(DISTRICT MAGISTRAE BAREILLY_IDA),JITIN PRASADA,PILIBHIT,NaN,2025-05-01,2025-06-06,349181.0,Physical Inspection,Crematoriums/energy efficient crematoriums or ...,MP18392,2025-2026
31663,Normal/Others,195622,Uttar Pradesh,BAREILLY(DISTRICT MAGISTRAE BAREILLY_IDA),JITIN PRASADA,PILIBHIT,NaN,2025-05-01,2025-06-06,349090.0,Physical Inspection,Crematoriums/energy efficient crematoriums or ...,MP18392,2025-2026
39694,Normal/Others,209334,Manipur,IMPHAL WEST(Deputy Commissioner Imphal West MP...,ANGOMCHA BIMOL AKOIJAM,INNER MANIPUR,NaN,2025-06-17,2025-07-08,6000000.0,Work Completed,Installing community drinking water plants,MP18371,2025-2026
39840,Normal/Others,209847,Manipur,IMPHAL WEST(Deputy Commissioner Imphal West MP...,ANGOMCHA BIMOL AKOIJAM,INNER MANIPUR,NaN,2025-06-17,2025-07-08,550000.0,Work Completed,Purchase of motor boats for flood and cyclone ...,MP18371,2025-2026
40792,Normal/Others,211430-Construction of bus-sheds or bus,Madhya Pradesh,DHAR(DISTRICT COLLECTOR DHAR_IDA),SAVITRI THAKUR,DHAR(ST),NaN,2025-06-23,2025-07-22,259942.0,Physical Inspection,stops,MP18102,2025-2026

In [108]:
# Correcting the Sanctioned data

Sanctioned["Work_Id"] = (
    Sanctioned["Work_Id"]
    .str.extract(r"(\d+)", expand=False)
)
Sanctioned[Sanctioned["Work_Id"].str.contains("-", na=False)]

Empty DataFrame
Columns: [Work category, Work_Id, State, IDA, Hon'ble Members of Parliament, Constituency, Work description, Recommended date, Sanction Date, Sanction Amount ( ₹ ), Work Status, Work, MP_ID, Financial_Year]
Index: []

In [109]:
Sanctioned.isnull().sum()

Work category                     0
Work_Id                           1
State                             0
IDA                               0
Hon'ble Members of Parliament     0
Constituency                      0
Work description                 98
Recommended date                  1
Sanction Date                     1
Sanction Amount ( ₹ )             0
Work Status                       0
Work                              1
MP_ID                             1
Financial_Year                    1
dtype: int64

In [110]:
# 1. Drop "Grand Total" Rows from all datasets
print("Cleaning Grand Total rows...")
for name, df in zip(['Expenditure', 'Completed', 'Recommended', 'Sanctioned'], 
                    [Expenditure, Completed, Recommended, Sanctioned]):
    if len(df) > 0 and df.iloc[-1].astype(str).str.contains('Grand Total').any():
        df.drop(df.tail(1).index, inplace=True)
        print(f"Dropped Grand Total from {name}")

Cleaning Grand Total rows...
Dropped Grand Total from Expenditure

In [111]:
# 2. Standardize Expenditure Dataset keys before join
Expenditure.rename(columns={"Work ID": "Work_Id"}, inplace=True)

# Extract MP_ID, Financial_Year, and true numerical Work_Id
if 'Work_Id' in Expenditure.columns and Expenditure['Work_Id'].str.contains('/', na=False).any():
    Expenditure[["MP_ID", "Financial_Year"]] = Expenditure["Work_Id"].str.split("/", expand=True).iloc[:, 1:3]
    Expenditure['Work_Id'] = Expenditure['Work_Id'].str.split("/").str[3]
    Expenditure["MP_ID"] = Expenditure["MP_ID"].str.strip()
    
Expenditure[['Work_Id', 'MP_ID', 'Financial_Year', 'Fund Disbursed Amount ( ₹ )']].head(3)

  Work_Id    MP_ID Financial_Year Fund Disbursed Amount ( ₹ )
0  233777  MP18218      2025-2026                    799146.0
1  233878  MP18218      2025-2026                    832080.0
2  233781  MP18218      2025-2026                    498309.0

In [112]:
# 3. Aggregate Expenditure to fix 1-to-Many Relationship
# So that we have 1 row per Work, which is required for tabular ML

# Ensure proper types
Expenditure['Expenditure Date'] = pd.to_datetime(Expenditure['Expenditure Date'], format="%d-%b-%Y", errors='coerce')
# Convert everything to string first, replace commas, then convert back to numeric
Expenditure['Fund Disbursed Amount ( ₹ )'] = pd.to_numeric(
    Expenditure['Fund Disbursed Amount ( ₹ )'].astype(str).str.replace(',', ''), 
    errors='coerce'
)

# Aggregate the payments per Work_Id
Expenditure_Agg = Expenditure.groupby('Work_Id').agg(
    Total_Fund_Disbursed=('Fund Disbursed Amount ( ₹ )', 'sum'),
    Payment_Count=('Work_Id', 'count'),
    Latest_Payment_Date=('Expenditure Date', 'max')
).reset_index()

Expenditure_Agg.head()

  Work_Id  Total_Fund_Disbursed  Payment_Count Latest_Payment_Date
0  133166              497185.0              1          2024-10-15
1  133191              850909.0              1          2026-03-05
2  133301              398009.0              1          2025-05-30
3  133303              399104.0              1          2025-05-30
4  133304              396154.0              1          2025-10-05

In [113]:
# 4. Check for True Duplicates
print("Duplicates in Completed: ", Completed[Completed['Work_Id'].notna()].duplicated(subset=['Work_Id']).sum())
print("Duplicates in Recommended: ", Recommended[Recommended['Work_Id'].notna()].duplicated(subset=['Work_Id']).sum())
print("Duplicates in Sanctioned: ", Sanctioned[Sanctioned['Work_Id'].notna()].duplicated(subset=['Work_Id']).sum())
print("Duplicates in Expenditure_Agg: ", Expenditure_Agg[Expenditure_Agg['Work_Id'].notna()].duplicated(subset=['Work_Id']).sum())

# If duplicates exist (e.g. data pipeline error), you can remove them using:
# Completed = Completed.drop_duplicates(subset=['Work_Id'], keep='first')

Duplicates in Completed:  0
Duplicates in Recommended:  0
Duplicates in Sanctioned:  0
Duplicates in Expenditure_Agg:  0

In [114]:
# 5. Clean Null Work_Ids from RIGHT tables to avoid Cartesian Explosions
# We keep nulls in 'Recommended' (our left table) but drop them from the joining tables
Sanctioned = Sanctioned.dropna(subset=['Work_Id']).copy()
Completed = Completed.dropna(subset=['Work_Id']).copy()
Expenditure_Agg = Expenditure_Agg.dropna(subset=['Work_Id']).copy()

# 6. Prevent Column Duplicate Chaos (e.g. State_x, State_y)
# We drop general metadata from the right tables because 'Recommended' already has it.
cols_to_drop = [
    "State", "IDA", "Hon'ble Members of Parliament", "Constituency", 
    "Work category", "Work Category", "Work description", "Work Description", 
    "Recommended date", "Work", "MP_ID", "Financial_Year"
]

Sanctioned_clean = Sanctioned.drop(columns=[col for col in cols_to_drop if col in Sanctioned.columns])
Completed_clean = Completed.drop(columns=[col for col in cols_to_drop if col in Completed.columns])

In [115]:
# 7. Perform the Left Joins (The Master Merge)
print(f"Initial Recommended Records: {len(Recommended)}")

# Step 1: Recommended + Sanctioned
# We use suffixes just in case there are other overlap columns (like Sanction Date)
Master_Data = Recommended.merge(Sanctioned_clean, on='Work_Id', how='left', suffixes=('', '_Sanc'))

# Step 2: Result + Completed
Master_Data = Master_Data.merge(Completed_clean, on='Work_Id', how='left', suffixes=('', '_Comp'))

# Step 3: Result + Expenditure
Master_Data = Master_Data.merge(Expenditure_Agg, on='Work_Id', how='left')

print(f"Final combined Records: {len(Master_Data)}")
Master_Data.head(3)

Initial Recommended Records: 106520
Final combined Records: 106520

,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Sanction Date,...,Financial_Year,Sanction Date_Sanc,Sanction Amount ( ₹ ),Work Status,Image,Completion Date,Amount Disbursed ( ₹ ),Total_Fund_Disbursed,Payment_Count,Latest_Payment_Date
0,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,2024-07-08,497185.0,09-Jul-2024,...,2024-2025,2024-07-09,497185.0,Physical Inspection,Images,2024-10-14,497185,497185.0,1.0,2024-10-15
1,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,2024-07-08,500000.0,18-Sep-2025,...,2025-2026,2025-09-18,500000.0,Sanction,NaN,NaT,NaN,NaN,NaN,NaT
2,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,2024-07-08,450000.0,23-Sep-2024,...,2024-2025,2024-09-23,450000.0,Sanction,NaN,NaT,NaN,NaN,NaN,NaT

In [116]:
Master_Data["is_Work_description"] = Master_Data["Work description"].notna().map({True: "Yes", False: "No"})

In [117]:
import numpy as np

# The condition: "Completion Date" is NOT null AND "Image" IS null
missing_image_condition = Master_Data["Completion Date"].notna() & Master_Data["Image"].isna()

# np.where(condition, value_if_true, value_if_false)
Master_Data["Completed_and_images"] = np.where(missing_image_condition, "No", "Yes")

In [118]:
Master_Data["District_IDA"] = Master_Data["IDA"].str.extract(r"^([^(]+)")[0].str.strip()
Master_Data

,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Sanction Date,...,Work Status,Image,Completion Date,Amount Disbursed ( ₹ ),Total_Fund_Disbursed,Payment_Count,Latest_Payment_Date,is_Work_description,Completed_and_images,District_IDA
0,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,2024-07-08,497185.0,09-Jul-2024,...,Physical Inspection,Images,2024-10-14,497185,497185.0,1.0,2024-10-15,Yes,Yes,DHARWAD
1,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,2024-07-08,500000.0,18-Sep-2025,...,Sanction,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,DHARWAD
2,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,2024-07-08,450000.0,23-Sep-2024,...,Sanction,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,DHARWAD
3,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,2024-07-08,1500000.0,29-May-2025,...,Work partially Completed,NaN,NaT,NaN,850909.0,1.0,2026-03-05,Yes,Yes,HAVERI
4,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,2024-07-09,398009.0,22-Aug-2024,...,Physical Inspection,Images,2025-02-03,398009,398009.0,1.0,2025-05-30,Yes,Yes,DHARWAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106515,Normal/Others,NaN,Telangana,HANUMAKONDA(DISTRICT COLLECTOR HANUMAKONDA_IDA),CHAMALA KIRAN KUMAR REDDY,BHONGIR,Providing CC Camera at velair village,2025-09-13,499000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,HANUMAKONDA
106516,Normal/Others,NaN,Telangana,NIZAMABAD(DISTRICT COLLECTOR NIZAMABAD_IDA),Arvind Dharmapuri,NIZAMABAD,Construction of Community hall in BC wada40,2024-10-28,400000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,NIZAMABAD
106517,Normal/Others,NaN,Telangana,JANGOAN(DISTRICT COLLECTOR JANGAON_IDA),Kishan Reddy Gangapuram,SECUNDERABAD,Laying of CC Road from R&B BT Road at Mamidala...,2026-06-22,1000000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,JANGOAN
106518,Normal/Others,NaN,Telangana,RAJANNA SIRCILLA(DISTRICT COLLECTOR RAJANNA SI...,VAMSI KRISHNA GADDAM,PEDDAPALLE,Drilling of borewell and Fitting of pump set a...,2026-07-13,250000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,RAJANNA SIRCILLA
106519,,NaN,,,,,,NaT,,"57,08,49,11,299.85",...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,

In [119]:
# 8. Fix Work_Id column (Extract numeric ID and move appended text)
print("Fixing 4,535 corrupted Work_Ids...")

# Identify rows with a dash in Work_Id
mask = Master_Data['Work_Id'].astype(str).str.contains('-', na=False)

# Extract the text appended after the dash
appended_text = Master_Data.loc[mask, 'Work_Id'].str.split('-', n=1).str[1].str.strip()

# Create 'Work' column if it doesn't already exist
if 'Work' not in Master_Data.columns:
    Master_Data['Work'] = None

# Move text to 'Work' column ONLY where it is currently missing (isna)
missing_work_mask = mask & Master_Data['Work'].isna()
Master_Data.loc[missing_work_mask, 'Work'] = appended_text[Master_Data['Work'].isna()]

# Extract the purely numeric ID before the dash to fix the Work_Id column
Master_Data.loc[mask, 'Work_Id'] = Master_Data.loc[mask, 'Work_Id'].str.split('-', n=1).str[0].str.strip()

print(f"Fixed {mask.sum()} rows successfully!")
Master_Data[mask].head(3)

Fixing 4,535 corrupted Work_Ids...
Fixed 4535 rows successfully!

,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Sanction Date,...,Work Status,Image,Completion Date,Amount Disbursed ( ₹ ),Total_Fund_Disbursed,Payment_Count,Latest_Payment_Date,is_Work_description,Completed_and_images,District_IDA
117,Normal/Others,133940,Bihar,MADHUBANI(DISTRICT PLANNING OFFICER MADHUBANI_...,Ramprit Mandal,JHANJHARPUR,khajauli hospital chowk ke pass Pre Fabricated...,2024-07-23,1451000.0,21-Feb-2025,...,NaN,NaN,2025-09-26,1451000,NaN,NaN,NaT,Yes,No,MADHUBANI
118,Normal/Others,133941,Bihar,MADHUBANI(DISTRICT PLANNING OFFICER MADHUBANI_...,Ramprit Mandal,JHANJHARPUR,Basopatti babhan dey chowk ke pass Pre Fabric...,2024-07-23,1451000.0,21-Feb-2025,...,NaN,NaN,2025-09-26,1451000,NaN,NaN,NaT,Yes,No,MADHUBANI
119,Normal/Others,133944,Bihar,MADHUBANI(DISTRICT PLANNING OFFICER MADHUBANI_...,Ramprit Mandal,JHANJHARPUR,paduma chowk ke pass Pre Fabricated bus sheds...,2024-07-23,1451000.0,21-Feb-2025,...,NaN,NaN,2025-09-26,1451000,NaN,NaN,NaT,Yes,No,MADHUBANI

In [120]:
Master_Data

,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Sanction Date,...,Work Status,Image,Completion Date,Amount Disbursed ( ₹ ),Total_Fund_Disbursed,Payment_Count,Latest_Payment_Date,is_Work_description,Completed_and_images,District_IDA
0,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,2024-07-08,497185.0,09-Jul-2024,...,Physical Inspection,Images,2024-10-14,497185,497185.0,1.0,2024-10-15,Yes,Yes,DHARWAD
1,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,2024-07-08,500000.0,18-Sep-2025,...,Sanction,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,DHARWAD
2,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,2024-07-08,450000.0,23-Sep-2024,...,Sanction,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,DHARWAD
3,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,2024-07-08,1500000.0,29-May-2025,...,Work partially Completed,NaN,NaT,NaN,850909.0,1.0,2026-03-05,Yes,Yes,HAVERI
4,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,2024-07-09,398009.0,22-Aug-2024,...,Physical Inspection,Images,2025-02-03,398009,398009.0,1.0,2025-05-30,Yes,Yes,DHARWAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106515,Normal/Others,NaN,Telangana,HANUMAKONDA(DISTRICT COLLECTOR HANUMAKONDA_IDA),CHAMALA KIRAN KUMAR REDDY,BHONGIR,Providing CC Camera at velair village,2025-09-13,499000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,HANUMAKONDA
106516,Normal/Others,NaN,Telangana,NIZAMABAD(DISTRICT COLLECTOR NIZAMABAD_IDA),Arvind Dharmapuri,NIZAMABAD,Construction of Community hall in BC wada40,2024-10-28,400000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,NIZAMABAD
106517,Normal/Others,NaN,Telangana,JANGOAN(DISTRICT COLLECTOR JANGAON_IDA),Kishan Reddy Gangapuram,SECUNDERABAD,Laying of CC Road from R&B BT Road at Mamidala...,2026-06-22,1000000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,JANGOAN
106518,Normal/Others,NaN,Telangana,RAJANNA SIRCILLA(DISTRICT COLLECTOR RAJANNA SI...,VAMSI KRISHNA GADDAM,PEDDAPALLE,Drilling of borewell and Fitting of pump set a...,2026-07-13,250000,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,RAJANNA SIRCILLA
106519,,NaN,,,,,,NaT,,"57,08,49,11,299.85",...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,

In [121]:
Master_Data.drop(columns=["Sanction Date"], inplace=True)

In [122]:
Master_Data["RECOMMENDED AMOUNT   ( ₹ )"] = pd.to_numeric(
    Master_Data["RECOMMENDED AMOUNT   ( ₹ )"].str.replace("\xa0", "", regex=False),
    errors="coerce"
)
Master_Data

,Work category,Work_Id,State,IDA,Hon'ble Members of Parliament,Constituency,Work description,Recommended date,RECOMMENDED AMOUNT ( ₹ ),Work,...,Work Status,Image,Completion Date,Amount Disbursed ( ₹ ),Total_Fund_Disbursed,Payment_Count,Latest_Payment_Date,is_Work_description,Completed_and_images,District_IDA
0,Normal/Others,133166,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan at Navalgund ...,2024-07-08,NaN,Construction of buildings for community cultur...,...,Physical Inspection,Images,2024-10-14,497185,497185.0,1.0,2024-10-15,Yes,Yes,DHARWAD
1,Trust and Society,133167,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of College room of CBS Charitabl...,2024-07-08,NaN,Construction of rooms and halls in school and ...,...,Sanction,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,DHARWAD
2,Trust and Society,133190,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Community Bhavan of Veerashaiv...,2024-07-08,NaN,Construction of buildings for community cultur...,...,Sanction,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,DHARWAD
3,Normal/Others,133191,Karnataka,HAVERI(DEPUTY COMMISSIONER HAVERI_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Maremma Cultural bhavan at Nee...,2024-07-08,NaN,Construction of buildings for community cultur...,...,Work partially Completed,NaN,NaT,NaN,850909.0,1.0,2026-03-05,Yes,Yes,HAVERI
4,Normal/Others,133301,Karnataka,DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA),Pralhad Venkatesh Joshi,DHARWAD,Construction of Cultural Bhavan at Kundagol TQ...,2024-07-09,NaN,Construction of buildings for community cultur...,...,Physical Inspection,Images,2025-02-03,398009,398009.0,1.0,2025-05-30,Yes,Yes,DHARWAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106515,Normal/Others,NaN,Telangana,HANUMAKONDA(DISTRICT COLLECTOR HANUMAKONDA_IDA),CHAMALA KIRAN KUMAR REDDY,BHONGIR,Providing CC Camera at velair village,2025-09-13,499000.0,Providing CCTV camera system for security of p...,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,HANUMAKONDA
106516,Normal/Others,NaN,Telangana,NIZAMABAD(DISTRICT COLLECTOR NIZAMABAD_IDA),Arvind Dharmapuri,NIZAMABAD,Construction of Community hall in BC wada40,2024-10-28,400000.0,Construction of community centers and communit...,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,NIZAMABAD
106517,Normal/Others,NaN,Telangana,JANGOAN(DISTRICT COLLECTOR JANGAON_IDA),Kishan Reddy Gangapuram,SECUNDERABAD,Laying of CC Road from R&B BT Road at Mamidala...,2026-06-22,1000000.0,"Construction of roads, link roads, pathways or...",...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,JANGOAN
106518,Normal/Others,NaN,Telangana,RAJANNA SIRCILLA(DISTRICT COLLECTOR RAJANNA SI...,VAMSI KRISHNA GADDAM,PEDDAPALLE,Drilling of borewell and Fitting of pump set a...,2026-07-13,250000.0,wells and borewells,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,RAJANNA SIRCILLA
106519,,NaN,,,,,,NaT,NaN,NaN,...,NaN,NaN,NaT,NaN,NaN,NaN,NaT,Yes,Yes,

In [124]:
# 1. Cast to String safely, then extract (ST) or (SC)
Master_Data['Constituency_Reservation'] = Master_Data['Constituency'].astype(str).str.extract(r'\((ST|SC)\)')[0]

# 2. Assign 'General' to everything that didn't match (and is not originally missing)
Master_Data.loc[Master_Data['Constituency'].notna() & Master_Data['Constituency_Reservation'].isna(), 'Constituency_Reservation'] = 'General'

# 3. Clean the Original Constituency Name safely
Master_Data['Constituency'] = Master_Data['Constituency'].astype(str).str.replace(r'\s*\((ST|SC)\)\s*', '', regex=True).str.strip()
Master_Data.loc[Master_Data['Constituency'] == 'nan', 'Constituency'] = None # Revert 'nan' strings back to None

# 4. Now print it!
Master_Data[['Constituency', 'Constituency_Reservation']].dropna().drop_duplicates().head(10)

       Constituency Constituency_Reservation
0           DHARWAD                  General
15           ARARIA                  General
16        BALURGHAT                  General
17            DAHOD                       ST
82         FARIDKOT                       SC
105        KHARGONE                       ST
117     JHANJHARPUR                  General
141           BUXAR                  General
153  PATHANAMTHITTA                  General
167          KOLLAM                  General

In [127]:
Master_Data.to_csv('MPLADS_Data.csv')